[package]
name = "bye_pcl_rs"
version = "0.1.3"
edition = "2021"
# 可免费商用
license-file = "./LICENSE"
keywords = [
    "pointcloud",
    "machine-learning",
    "filter",
    "segmentation",
    "tracking",
]
description = "The Point Cloud Library (PCL) is a standalone, large scale, open project for 2D/3D image and point cloud processing.Implemented in pure Rust."
authors = ["qsbye"]
homepage = "https://docs.rs/bye_pcl_rs"
documentation = "https://docs.rs/bye_pcl_rs"
repository = "https://github.com/ByeIO/bye.pcl.rs"
readme = "README.md"
exclude = ["git", "assets"]

[dependencies]
# 线性代数
nalgebra = "0.33.2"
# 异常处理
anyhow = "1.0.95"
eyre = "0.6.12"
# 二进制编码
base64 = "0.22.1"
# 数学特性
num-traits = "0.2.19"
# 随机数
rand = { version = "0.9.0" }
rand_distr = "0.5.0"
# 序列化
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
# 多线程
tokio = "1.43.0"
# 命令行参数解析
cpal = "0.15.3"
# kdtree数据结构
kd-tree = { version = "0.6.0", features = [
    "serde",
    "nalgebra",
    "nalgebra-serde",
] }
# 机器学习,数据分析最佳实践算法整合包
rstats = "2.1.12"
# fft快速傅立叶变换算法
realfft = "3.4.0"
# 宏编程/元编程
proc-macro2 = "1.0.93"
paste = "1.0.15"
syn = { version = "2.0.98", features = ["full"] }
quote = { version = "1.0.38", features = [] }
# 浮点数精度处理
approx = "0.5.1"
# 复数支持
num-complex = "0.4.6"
# 点云pcd文件处理
bye_pcd_rs = { version = "0.12.1" }
# 点云ply文件处理
ply-rs-bw = "2.0.1"
# 计数工具
typenum = "1.17.0"
# 泊松表面重建
poisson_reconstruction = { version = "0.3.1", features = ["serde", "serde-serialize"] }
# NURBS曲线/表面建模库
curvo = { version = "0.1.49", features = ["serde"] }
# f3l系列算法包
f3l_filter = { version = "0.2.0", features = ["app_kiss3d"] }
f3l_core = { version = "0.3.0" }
f3l_surface = "0.2.0"
f3l_features = { version = "0.2.2", features = ["app_kiss3d"] }
f3l_glam = "0.1.1"
f3l_search_tree = { version = "0.3.1", features = ["app_kiss3d"] }
f3l_segmentation = { version = "0.2.1", features = ["app_kiss3d"] }

[dev-dependencies]
# 性能评测
criterion = { version = "0.5.1", features = ["html_reports", "plotters", "cargo_bench_support"],default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
# 性能评测
criterion = { version = "0.5.1", features = ["rayon"] }

# [target.'cfg(not(target_arch = "wasm32"))'.patch.crates-io]
# # 依赖覆盖, 正常目标使用正常的库
# getrandom = { version = "0.3.1", path="./static/getrandom"}

# [target.'cfg(target_arch = "wasm32")'.patch.crates-io]
# # 依赖覆盖, 魔改版
# getrandom = { version = "0.3.1", path="./static/getrandom_wyhash" }

[patch.crates-io]
# 依赖覆盖, 魔改版
getrandom = { version = "0.3.1", path="./static/getrandom_wyhash" }

[lib]
# 支持派生宏, 过程宏, 属性宏
proc-macro = false
# crate类型必须为cdylib以编译到wasm32-unknown-unknown
crate-type = ["cdylib", "rlib"]
